### ISSUE TITLE
Code does not compile

### ISSUE THREAD

**Issue by antoyo** [githwxi/ATS-Postiats#196]
Hi.
The following code does not work:
```ats
extern
fun
int_foreach
(n0: int, fwork: cfun(int, void)): void
```
from [this page](http://ats-lang.sourceforge.net/DOCUMENT/ATS2FUNCRASH/HTML/c250.html) does not compile.
I get the following error:
```
ATS/CrashIntoFP/Ch5/ch5.dats: 187(line=11, offs=10) -- 191(line=11, offs=14): error(2): unrecognized static identifier [cfun].
ATS/CrashIntoFP/Ch5/ch5.dats: 187(line=11, offs=10) -- 202(line=11, offs=25): error(2): the static expression needs to be impredicative but is assigned the sort [S2RTerr()].
ATS/CrashIntoFP/Ch5/ch5.dats: 269(line=13, offs=1) -- 423(line=21, offs=2): error(2): the template is expected to be fully applied but it is not.
```

Also, the following code, in the same chapter, does not work either:
```ats
extern
fun
int_foreach_method
(n0: int)(fwork: cfun(int, void)): void
//
extern
fun
{res:t@ype}
int_foldleft_method
(n0: int, ty: TYPE(res))
(res: res, fopr: cfun(res, int, res)): res
//
overload .foreach with int_foreach_method
overload .foldleft with int_foldleft_method
//

//
fun fact(n: int): int =
(n).foldleft(TYPE{int})(lam(res, i) => res*(i+1))
//
fun testfact(n: int): int =
(n).foreach()(lam(i) => println! ("fact(", i+1, ") = ", fact(i+1)))
//
```
with the following error:
```
ATS/CrashIntoFP/Ch5/ch5.dats: 2684(line=97, offs=2) -- 2732(line=97, offs=50): error(3): the symbol [.foldleft] cannot be resolved as no match is found.
ATS/CrashIntoFP/Ch5/ch5.dats: 2684(line=97, offs=2) -- 2732(line=97, offs=50): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g0int_t0ype); S2Eextkind(atstype_int))].
ATS/CrashIntoFP/Ch5/ch5.dats: 2684(line=97, offs=2) -- 2732(line=97, offs=50): error(3): mismatch of static terms (tyleq):
The actual term is: S2Eerrexp()
The needed term is: S2Eapp(S2Ecst(g0int_t0ype); S2Eextkind(atstype_int))
ATS/CrashIntoFP/Ch5/ch5.dats: 2825(line=100, offs=62) -- 2828(line=100, offs=65): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g0int_t0ype); S2Eextkind(atstype_int))].
ATS/CrashIntoFP/Ch5/ch5.dats: 2825(line=100, offs=62) -- 2828(line=100, offs=65): error(3): mismatch of static terms (tyleq):
The actual term is: S2Eapp(S2Ecst(g1uint_int_t0ype); S2Eextkind(atstype_size), S2Eapp(S2Ecst(add_int_int); S2EVar(8795), S2Eintinf(1)))
The needed term is: S2Eapp(S2Ecst(g0int_t0ype); S2Eextkind(atstype_int))
ATS/CrashIntoFP/Ch5/ch5.dats: 2765(line=100, offs=2) -- 2831(line=100, offs=68): error(3): the symbol [.foreach] cannot be resolved due to too many matches:
D2ITMcst(int_foreach_method) of 0
D2ITMcst(int_foreach_method) of 0
ATS/CrashIntoFP/Ch5/ch5.dats: 2765(line=100, offs=2) -- 2831(line=100, offs=68): error(3): the dynamic expression cannot be assigned the type [S2Eapp(S2Ecst(g0int_t0ype); S2Eextkind(atstype_int))].
ATS/CrashIntoFP/Ch5/ch5.dats: 2765(line=100, offs=2) -- 2831(line=100, offs=68): error(3): mismatch of static terms (tyleq):
The actual term is: S2Eerrexp()
The needed term is: S2Eapp(S2Ecst(g0int_t0ype); S2Eextkind(atstype_int))
ATS/CrashIntoFP/Ch5/ch5.dats: 2863(line=104, offs=5) -- 2875(line=104, offs=17): error(3): the dynamic expression cannot be assigned the type [S2Ecst(atsvoid_t0ype)].
ATS/CrashIntoFP/Ch5/ch5.dats: 2863(line=104, offs=5) -- 2875(line=104, offs=17): error(3): mismatch of static terms (tyleq):
The actual term is: S2Eapp(S2Ecst(g0int_t0ype); S2Eextkind(atstype_int))
The needed term is: S2Ecst(atsvoid_t0ype)
patsopt(TRANS3): there are [6] errors in total.
exit(ATS): uncaught exception: _2tmp_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)
```
Thanks to fix this issue.

By the way, the code of the factorial is wrong:
```ats
fix f(x: int): int => if x > 0 then x * f(x) else 1
```
It should be:
```ats
fix f(x: int): int => if x > 0 then x * f(x - 1) else 1
```

**Comment by githwxi** [comment]
I fixed the factorial example. Thanks!

What is the content of your ch5.dats file?

It seems that you did not include the needed library to get the code working.

**Comment by antoyo** [comment]
Here's the content:
```ats
#include "share/atspre_staload.hats"
#include "share/atspre_staload_libats_ML.hats"

val square = lam(x: int): int => x * x

extern fun int_foreach(n: int, f: (int) -<cloref1> void): void

implement int_foreach(n, f) =
    loop(0) where {
        fun loop(i: int): void =
            if i < n then (
                f(i);
                loop(i + 1)
            )
            else
                ()
    }

fun {res: t@ype} int_foldleft(n: int, res: res, f: (res, int) -<cloref1> res): res =
    loop(res, 0) where {
        fun loop(res: res, i: int): res =
            if i < n then
                loop(f(res, i), i + 1)
            else
                res
    }

extern fun int_cross_foreach(m: int, n: int, f: (int, int) -<cloref1> void): void

implement int_cross_foreach(m, n, f) =
    int_foreach(m, lam(i) => int_foreach(n, lam(j) => f(i, j)))

fun {a: t@ype} matrix_mulby(p: int, q: int, r: int, a: matrix0(a), b: matrix0(a), c: matrix0(a)): void =
    let val add = gadd_val_val<a>
        val mul = gmul_val_val<a>
        fun f(i: int, j: int): void =
            c[i, j] := int_foldleft<a>(q, c[i, j], lam(res, k) => add(res, mul(a[i, k], b[k, j])))
    in
        int_cross_foreach(p, r, lam(i, j) => f(i, j))
    end

fun sq(i: int): int = i * i

fun sqsum(n: int): int =
    int_foldleft<int>(n, 0, lam(res, i) => res + sq(i + 1))

extern fun int_foreach_method(n: int)(f: (int) -<cloref1> void): void

extern fun {res: t@ype} int_foldleft_method(n0: int, ty: TYPE(res))(res: res, f: (res, int) -<cloref1> res): res

overload .foreach with int_foreach_method
overload .foldleft with int_foldleft_method

fun fact(n:int): int =
    (n).foldleft(TYPE{int})(lam(res, i) => res * (i + 1))

fun testfact(n: int): void =
    int_foreach(n, lam(i) => println!("fact(", i, ") = ", fact(i)))

implement main0 () = (
    testfact(20)
)
```
Thanks for your help.

**Comment by githwxi** [comment]
I tried your code. It showed different error message from what your mentioned earlier.

In the above code, .foldleft should be replaced with .myfoldleft (as the formed has been used in libats/ML).
The same applies to .foreach. You have not implemented int_foldleft_method yet, so the compiler complains
when compiling the code.

**Comment by antoyo** [comment]
Hum, even with your proposed changes, I still get the same error.
Here's the new code:
```ats
extern fun {res: t@ype} int_foldleft_method(n0: int, ty: TYPE(res))(res: res, f: (res, int) -<cloref1> res): res

implement {res} int_foldleft_method(n0, _) =
    lam (res, f) =>
        loop(res, 0) where {
            fun loop(res: res, i: int): res =
                if i < n0 then
                    loop(f(res, i), i + 1)
                else
                    res
        }

overload .my_foldleft with int_foldleft_method

fun fact(n:int): int =
    (n).my_foldleft(TYPE{int})(lam(res, i) => res * (i + 1))
```
and the error is:
```
the symbol [.my_foldleft] cannot be resolved as no match is found.
```
Thanks for your help.

**Comment by githwxi** [comment]
(lam(res, i) => res * (i + 1))

should be

(1, lam(res, i) => res * (i + 1))

**Comment by antoyo** [comment]
Oh, thank you.
Now everything works.
Could you please fix this in the book as it is written:
```ats
fun fact(n: int): int =
(n).foldleft(TYPE{int})(lam(res, i) => res*(i+1))
```
Also, I think the error message should tell that there is a mismatch between the number of arguments.
Is it okay if I leave this issue opened to mention the other errors I find in the tutorial?

**Comment by githwxi** [comment]
Sure. I fixed the issue.
